services:
  # A server representing a remote backup location
  backup-server:
    build:
      context: ./backup-server
    container_name: backup-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - USER_NAME=operator
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=pass
    ports:
      - "2222:22"
    networks:
      lab-net:
        ipv4_address: 172.25.0.10

  # A production server with data and tools
  prod-server:
    build:
      context: ./prod-server
    container_name: prod-server
    volumes:
      - ./data:/data
    networks:
      lab-net:
        ipv4_address: 172.25.0.20

  # A target for performance testing
  traffic-gen:
    image: alpine:latest
    container_name: traffic-gen
    networks:
      lab-net:
        ipv4_address: 172.25.0.30
    command: sh -c "apk add iperf3 && iperf3 -s"

  # A private service (isolated)
  private-db:
    image: alpine:latest
    container_name: private-db
    networks:
      lab-net:
        ipv4_address: 172.25.0.40
    command: sh -c "apk add python3 && echo 'DB SECRET' > secret.txt && python3 -m http.server 5432"

  # Load Balancer
  balancer:
    image: nginx:alpine
    container_name: balancer
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      lab-net:
        ipv4_address: 172.25.0.100

networks:
  lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
