events {
    worker_connections 1024;
}

http {
    upstream backup_sync {
        server 172.25.0.20:80;
        server 172.25.0.10:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backup_sync;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
